Repository dell/csi-baremetal, pull requests merged in 2020-12, with the labels that each got.

#180 [ISSUE-179] manage system lvg finalizers
  pkg/base/util/volume_helper.go
  pkg/crcontrollers/lvg/lvgcontroller.go
  pkg/crcontrollers/lvg/lvgcontroller_test.go
  pkg/node/volumemgr.go
Labels: enhancement

#182 [Issue-181] Add support for event config
  charts/baremetal-csi-plugin/templates/baremetal-csi-node.yaml
  charts/baremetal-csi-plugin/values.yaml
  pkg/events/events.go
  pkg/events/events_test.go
Labels: enhancement

#183 [ISSUE-161] base flow of drive replacement process
  api/v1/constants.go
  api/v1/drivecrd/drive_types.go
  api/v1/types.proto
  charts/baremetal-csi-plugin/crds/baremetal-csi.dellemc.com_drives.yaml
  charts/baremetal-csi-plugin/crds/baremetal-csi.dellemc.com_volumes.yaml
  cmd/node/main.go
  pkg/common/volume_operations.go
  pkg/common/volume_operations_test.go
  pkg/controller/controller.go
  pkg/crcontrollers/csibmnode/controller.go
  pkg/crcontrollers/drive/drivecontroller.go
  pkg/node/provisioners/drive_provisioner.go
  pkg/node/volumemgr.go
  pkg/node/volumemgr_test.go
  test/app/nginx.yaml
Labels: enhancement

#196 [ISSUE-161] isSystem is overwritten
  api/v1/drivecrd/drive_types.go
  pkg/node/volumemgr.go
Labels: bug

#191 [ISSUE-186] Issue with drive removed=true was caused by resizing
  pkg/drivemgr/loopbackmgr/loopbackmgr.go
  pkg/drivemgr/loopbackmgr/loopbackmgr_test.go
Labels: bug

#197 [Issue-195] Available capacity CR is removed when volume provisioned
  pkg/node/volumemgr.go
  pkg/node/volumemgr_test.go
Labels: bug

#193 [Issue-184] Handle recovery failure
  api/v1/constants.go
  api/v1/drivecrd/drive_types.go
  cmd/node/main.go
  pkg/crcontrollers/drive/drivecontroller.go
  pkg/eventing/eventing.go
  pkg/node/volumemgr.go
Labels: enhancement

#194 [Issue-185] Add led manipulation
  cmd/node/main.go
  pkg/crcontrollers/drive/drivecontroller.go
  pkg/drivemgr/loopbackmgr/loopbackmgr.go
Labels: enhancement

#192 [ISSUE-176] support upgrade for loopbackmgr
  charts/baremetal-csi-plugin/templates/baremetal-csi-node.yaml
  charts/baremetal-csi-plugin/values.yaml
  cmd/drivemgr/loopbackmgr/main.go
  pkg/drivemgr/loopbackmgr/loopbackmgr.go
  pkg/drivemgr/loopbackmgr/loopbackmgr_test.go
Labels: bug

#199 [ISSUE-198] Update version to 0.0.12
  charts/baremetal-csi-plugin/Chart.yaml
  charts/csibm-operator/Chart.yaml
  charts/scheduler-extender/Chart.yaml
  charts/scheduler/Chart.yaml
  pkg/base/constants.go
  variables.mk
Labels: documentation

#201 [ISSUE-200] Remove drive DR when disk replacement completed successfully
  pkg/crcontrollers/drive/drivecontroller.go
  pkg/node/volumemgr.go
Labels: enhancement

#203 [ISSUE-204] Add LVG support to DR procedure
  api/v1/constants.go
  pkg/base/k8s/cr_helper.go
  pkg/base/k8s/cr_helper_test.go
  pkg/crcontrollers/drive/drivecontroller.go
  pkg/node/volumemgr.go
Labels: enhancement

#206 [ISSUE-205] Handle DeleteVolume request(s) failure
  api/v1/drivecrd/drive_types.go
  pkg/node/volumemgr.go
  pkg/node/volumemgr_test.go
Labels: enhancement

#212 [Issue-211] Implement disk ready for replacement alert
  pkg/crcontrollers/drive/drivecontroller.go
  pkg/eventing/eventing.go
Labels: enhancement

#210 [ISSUE-209] change openshift patcher logic
  docs/PULL_REQUEST_TEMPLATE.md
  pkg/scheduler/patcher/openshift_patcher.sh
Labels: enhancement

#215 [ISSUE-213] Implement GRPC handlers metrics for monitoring
  charts/baremetal-csi-plugin/templates/baremetal-csi-controller.yaml
  charts/baremetal-csi-plugin/templates/baremetal-csi-node.yaml
  charts/baremetal-csi-plugin/values.yaml
  cmd/controller/main.go
  cmd/drivemgr/basemgr/main.go
  cmd/drivemgr/idracmgr/main.go
  cmd/drivemgr/loopbackmgr/main.go
  cmd/node/main.go
  go.mod
  pkg/base/rpc/grpcclient.go
  pkg/base/rpc/grpcclient_test.go
  pkg/base/rpc/grpcserver.go
  pkg/base/rpc/grpcserver_test.go
  pkg/base/util/healthcheck.go
  pkg/base/util/healthcheck_test.go
  test/sanity/sanity_test.go
Labels: enhancement

#218 [ISSUE-217] Drive successfully replaced alert
  pkg/crcontrollers/drive/drivecontroller.go
  pkg/eventing/eventing.go
  pkg/events/events.go
Labels: enhancement

#219 [ISSUE-216] remove node annotations
  charts/csibm-operator/templates/csibm-rbac.yaml
  pkg/base/capacityplanner/readers_test.go
  pkg/common/ac_operations_test.go
  pkg/crcontrollers/csibmnode/controller.go
  pkg/crcontrollers/csibmnode/controller_test.go
  test/e2e/common/types.go
  test/e2e/scenarios/bare-metal-testdriver.go
Labels: enhancement

#221 [Issue-220] Change info type to normal type
  pkg/crcontrollers/drive/drivecontroller.go
  pkg/eventing/eventing.go
  pkg/node/volumemgr.go
  pkg/node/volumemgr_test.go
Labels: enhancement

#225 [ISSUE-106] Skip allocation for LVG in FAILED state by resetting AC size
  pkg/base/error/types.go
  pkg/base/k8s/cr_helper.go
  pkg/base/k8s/cr_helper_test.go
  pkg/crcontrollers/lvg/lvgcontroller.go
  pkg/node/volumemgr.go
Labels: bug

#223 [ISSUE-224] change lvg detection method
  pkg/base/constants.go
  pkg/base/linuxutils/lvm/lvm.go
  pkg/base/linuxutils/lvm/lvm_test.go
  pkg/base/util/common.go
  pkg/base/util/common_test.go
  pkg/mocks/linuxutils/lvm.go
  pkg/node/volumemgr.go
  pkg/node/volumemgr_test.go
Labels: bug
