Repository dell/csi-baremetal, pull requests merged in 2020-11, with the labels that each got.

#149 [Issue-147] lvremove might failed on big scale
  pkg/base/command/cmdexec.go
  pkg/base/linuxutils/lvm/lvm.go
  pkg/base/linuxutils/lvm/lvm_test.go
  pkg/mocks/executors.go
Labels: bug

#154 [ISSUE-124] use CSIBMNode controller
  Makefile.validation
  charts/baremetal-csi-plugin/templates/baremetal-csi-controller.yaml
  charts/baremetal-csi-plugin/templates/baremetal-csi-node.yaml
  cmd/node/main.go
  docs/README.md
  go.mod
  go.sum
  pkg/base/constants.go
  pkg/base/k8s/cr_helper.go
  pkg/base/k8s/kubeclient.go
  pkg/base/util/logging.go
  pkg/common/ac_operations.go
  pkg/common/volume_operations.go
  pkg/common/volume_operations_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/crcontrollers/csibmnode/common/const.go
  pkg/crcontrollers/csibmnode/controller.go
  pkg/crcontrollers/csibmnode/controller_test.go
  pkg/crcontrollers/lvg/lvgcontroller.go
  pkg/drivemgr/loopbackmgr/loopbackmgr.go
  pkg/node/node.go
  pkg/node/node_test.go
  pkg/node/provisioners/drive_provisioner.go
  pkg/node/volumemgr.go
  pkg/scheduler/extender/extender.go
  pkg/scheduler/extender/extender_test.go
  pkg/testutils/testutils.go
  test/e2e/baremetal_e2e_test.go
  test/e2e/common/bmtestcontext.go
  test/e2e/common/deploy-plugin-components.go
  test/e2e/common/util.go
  test/e2e/scenarios/bare-metal-testdriver.go
  test/e2e/scenarios/drive-health-change.go
  test/e2e/scenarios/scheduler-test.go
  test/e2e/scenarios/setup.go
  variables.mk
Labels: enhancement

#156 [ISSUE-155] update version to 0.0.11
  charts/baremetal-csi-plugin/Chart.yaml
  charts/csibm-operator/Chart.yaml
  charts/scheduler-extender/Chart.yaml
  charts/scheduler/Chart.yaml
  pkg/base/constants.go
  variables.mk
Labels: documentation

#157 Fix future linter errors
  cmd/node/main.go
  pkg/base/linuxutils/fs/fs_helper.go
  pkg/base/linuxutils/ipmi/ipmitool.go
  pkg/base/linuxutils/lsscsi/lsscsi.go
  pkg/base/linuxutils/nvmecli/nvmecli.go
  pkg/base/linuxutils/smartctl/smartctl.go
  pkg/base/util/convert.go
  pkg/base/util/signal_handler.go
  pkg/controller/controller.go
  pkg/controller/node/statemonitor.go
  pkg/drivemgr/basemgr/basemgr.go
  pkg/drivemgr/idracmgr/idracmgr.go
  pkg/drivemgr/loopbackmgr/loopbackmgr.go
  pkg/node/node.go
  test/e2e/scenarios/different-sc-test.go
Labels: chore

#158 Fix CI after golang update
  Makefile.validation
Labels: bug

#152 [Issue-151] Generate uuid for volumes CR
  pkg/node/volumemgr.go
Labels: bug

#160 [ISSUE-159] added op status for drive crd
  api/v1/constants.go
  api/v1/types.proto
  charts/baremetal-csi-plugin/crds/baremetal-csi.dellemc.com_drives.yaml
  pkg/node/volumemgr.go
Labels: enhancement

#146 [Issue-145] CSI should handle OpenShift system disks
  charts/baremetal-csi-plugin/templates/baremetal-csi-node.yaml
  charts/baremetal-csi-plugin/values.yaml
  pkg/base/constants.go
  pkg/node/volumemgr.go
  pkg/node/volumemgr_test.go
Labels: bug

#167 [ISSUE-166] Fix k8s client
  pkg/base/k8s/kubeclient.go
Labels: bug

#165 [ISSUE-150] Fix UT on cloud CI
  pkg/node/volumemgr_test.go
Labels: bug

#170 [ISSUE-169] Pull busybox not from the Dockerhub
  Makefile.validation
Labels: bug

#164 [ISSUE-162] Metrics proposal
  docs/proposals/metrics.md
Labels: discussion, enhancement

#172 [ISSUE-168] fix typo
  Makefile.validation
Labels: bug

#171 [ISSUE-168] extend drivemgr interface
  api/v1/constants.go
  api/v1/drivemgrsvc.proto
  pkg/drivemgr/basemgr/basemgr.go
  pkg/drivemgr/drivemgr.go
  pkg/drivemgr/drivemgr_service.go
  pkg/drivemgr/idracmgr/idracmgr.go
  pkg/drivemgr/loopbackmgr/loopbackmgr.go
  pkg/mocks/drivemgr.go
  pkg/node/volumemgr_test.go
Labels: enhancement

#175 [ISSUE-174] manually pull and load nginx image for e2e tests
  Makefile.validation
Labels: bug, chore

#178 [ATL-90] do not use non clean disk
  api/v1/constants.go
  pkg/base/k8s/cr_helper.go
  pkg/node/volumemgr.go
  pkg/node/volumemgr_test.go
Labels: bug
