Repository dell/csi-baremetal, pull requests merged in 2020-10, with the labels that each got.

#103 Add ability to uninstall scheduler extender on OpenShift
  pkg/scheduler/patcher/openshift_patcher.sh
Labels: bug, enhancement

#109 [ISSUE-93] update documentation
  charts/scheduler/values.yaml
  docs/CONTRIBUTING.md
  docs/PULL_REQUEST_TEMPLATE.md
  docs/README.md
Labels: documentation

#95 [ISSUE-111] Add system disk support
  api/v1/types.proto
  charts/baremetal-csi-plugin/crds/baremetal-csi.dellemc.com_drives.yaml
  cmd/drivemgr/basemgr/main.go
  pkg/base/k8s/kubeclient.go
  pkg/base/k8s/kubeclient_test.go
  pkg/common/ac_operations_test.go
  pkg/common/volume_operations.go
  pkg/drivemgr/basemgr/basemgr.go
  pkg/drivemgr/basemgr/basemgr_test.go
  pkg/lvm/lvgcontroller.go
  pkg/node/volumemgr.go
  pkg/node/volumemgr_test.go
Labels: enhancement

#104 Prioritize method in the extender
  charts/scheduler-extender/templates/patcher-configmap.yaml
  charts/scheduler-extender/templates/rbac.yaml
  pkg/scheduler/extender/extender.go
  pkg/scheduler/extender/extender_test.go
  pkg/scheduler/patcher/policy.yaml
  test/e2e/scenarios/scheduler-test.go
Labels: enhancement

#108 [ISSUE-110] Remove pods in e2e tests in parallel to speed up tests
  test/e2e/common/util.go
Labels: enhancement

#113 [ISSUE-112] switch version to 0.0.10
  charts/baremetal-csi-plugin/Chart.yaml
  charts/scheduler-extender/Chart.yaml
  charts/scheduler/Chart.yaml
  pkg/base/constants.go
  variables.mk
Labels: enhancement

#114 [Issue-99] Loopbackmgr does not handle node reboot correctly
  cmd/controller/main.go
  cmd/drivemgr/setup.go
  cmd/node/main.go
  pkg/base/util/signal_handler.go
  pkg/drivemgr/loopbackmgr/loopbackmgr.go
  test/e2e/common/util.go
  test/e2e/scenarios/bare-metal-testdriver.go
  test/e2e/scenarios/node-reboot.go
Labels: bug

#115 [ISSUE-98] add NR proposal
  docs/proposals/TEMPLATE.md
  docs/proposals/node_replacement.md
Labels: documentation, enhancement

#118 [Issue-82] Take into account drives vid and pid when drive path is searched
  pkg/base/linuxutils/lsblk/lsblk.go
  pkg/base/linuxutils/lsblk/lsblk_test.go
  pkg/node/volumemgr.go
  pkg/node/volumemgr_test.go
Labels: enhancement

#121 [Issue-117] Create csi-baremetal.nodes CRD
  Makefile
  api/v1/csibmnodecrd/csibmnode_types.go
  api/v1/csibmnodecrd/groupversion_info.go
  api/v1/types.proto
  charts/baremetal-csi-plugin/crds/baremetal-csi.dellemc.com_csibmnodes.yaml
  pkg/base/k8s/kubeclient.go
Labels: enhancement

#116 [ISSUE-96] Add support for capacity reservation to csi-controller
  charts/scheduler-extender/templates/patcher-configmap.yaml
  charts/scheduler-extender/templates/scheduler-extender.yaml
  charts/scheduler-extender/values.yaml
  cmd/controller/main.go
  cmd/node/main.go
  cmd/scheduling/extender/main.go
  docs/README.md
  pkg/base/capacityplanner/common.go
  pkg/base/capacityplanner/helpers.go
  pkg/base/capacityplanner/helpers_test.go
  pkg/base/capacityplanner/mocks.go
  pkg/base/capacityplanner/node_capacity.go
  pkg/base/capacityplanner/placing_plan.go
  pkg/base/capacityplanner/planner.go
  pkg/base/capacityplanner/planner_test.go
  pkg/base/capacityplanner/readers.go
  pkg/base/capacityplanner/readers_test.go
  pkg/base/featureconfig/feature.go
  pkg/base/featureconfig/feature_test.go
  pkg/base/util/logging.go
  pkg/common/ac_operations.go
  pkg/common/ac_operations_test.go
  pkg/common/test_data.go
  pkg/common/volume_operations.go
  pkg/common/volume_operations_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/node/node.go
  pkg/node/node_test.go
  pkg/node/volumemgr.go
  pkg/scheduler/extender/extender.go
  pkg/scheduler/extender/extender_test.go
  test/e2e/scenarios/bare-metal-testdriver.go
  test/e2e/scenarios/scheduler-test.go
  test/sanity/sanity_test.go
Labels: enhancement

#130 [ISSUE-129] Ability to deploy CSI to labeled nodes
  charts/baremetal-csi-plugin/crds/baremetal-csi.dellemc.com_csibmnodes.yaml
  charts/baremetal-csi-plugin/templates/baremetal-csi-controller.yaml
  charts/baremetal-csi-plugin/templates/baremetal-csi-node.yaml
  charts/baremetal-csi-plugin/values.yaml
Labels: enhancement

#131 Fix typo in installation command in README.md
  docs/README.md
Labels: bug, documentation

#133 [ISSUE-132] Change scope for CRs from Namespaced to Cluster
  api/v1/acreservationcrd/availablecapacityreservation_types.go
  api/v1/availablecapacitycrd/availablecapacity_types.go
  api/v1/csibmnodecrd/csibmnode_types.go
  api/v1/drivecrd/drive_types.go
  api/v1/lvgcrd/lvg_types.go
  api/v1/volumecrd/volume_types.go
  charts/baremetal-csi-plugin/crds/baremetal-csi.dellemc.com_availablecapacities.yaml
  charts/baremetal-csi-plugin/crds/baremetal-csi.dellemc.com_availablecapacityreservations.yaml
  charts/baremetal-csi-plugin/crds/baremetal-csi.dellemc.com_csibmnodes.yaml
  charts/baremetal-csi-plugin/crds/baremetal-csi.dellemc.com_drives.yaml
  charts/baremetal-csi-plugin/crds/baremetal-csi.dellemc.com_lvgs.yaml
  charts/baremetal-csi-plugin/crds/baremetal-csi.dellemc.com_volumes.yaml
  cmd/node/main.go
  pkg/base/k8s/fake_kubeclient.go
  pkg/base/k8s/kubeclient.go
  pkg/base/k8s/kubeclient_test.go
  test/e2e/common/types.go
  test/e2e/scenarios/bare-metal-testdriver.go
  test/e2e/scenarios/drive-health-change.go
  test/e2e/scenarios/scheduler-test.go
Labels: enhancement

#125 [ISSUE-101] Drive Replacement proposal
  docs/proposals/drive-replacement.md
Labels: discussion, documentation

#140 [ISSUE-139] Fix ReservationHelper.ReleaseReservation method to remove right ACR
  pkg/base/capacityplanner/helpers.go
  pkg/base/capacityplanner/helpers_test.go
  pkg/common/volume_operations.go
Labels: bug

#135 [ISSUE-122] csibm node controller
  Makefile
  Makefile.docker
  api/v1/constants.go
  api/v1/types.proto
  charts/baremetal-csi-plugin/templates/baremetal-csi-controller.yaml
  charts/baremetal-csi-plugin/templates/baremetal-csi-node.yaml
  charts/baremetal-csi-plugin/values.yaml
  charts/csibm-operator/.helmignore
  charts/csibm-operator/Chart.yaml
  charts/csibm-operator/crds/baremetal-csi.dellemc.com_csibmnodes.yaml
  charts/csibm-operator/templates/csibm-controller.yaml
  charts/csibm-operator/templates/csibm-rbac.yaml
  charts/csibm-operator/values.yaml
  charts/scheduler-extender/templates/scheduler-extender.yaml
  charts/scheduler-extender/values.yaml
  cmd/csibmnode/main.go
  cmd/node/main.go
  cmd/scheduling/extender/main.go
  docs/README.md
  go.sum
  pkg/base/featureconfig/feature.go
  pkg/base/k8s/kubeclient.go
  pkg/base/logger.go
  pkg/common/volume_operations.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/crcontrollers/csibmnode/Dockerfile
  pkg/crcontrollers/csibmnode/controller.go
  pkg/crcontrollers/csibmnode/controller_test.go
  pkg/crcontrollers/lvg/lvgcontroller.go
  pkg/crcontrollers/lvg/lvgcontroller_test.go
  pkg/node/Makefile
  pkg/node/node.go
  pkg/node/node_test.go
  pkg/node/volumemgr.go
  pkg/scheduler/extender/extender.go
  pkg/scheduler/extender/extender_test.go
  variables.mk
Labels: enhancement

#142 [ISSUE-141] Replace capacityplanner.choseACinACRWithLessAC function with choseACFromOldestACR
  pkg/base/capacityplanner/helpers.go
  pkg/base/capacityplanner/helpers_test.go
  pkg/base/capacityplanner/planner.go
  pkg/base/capacityplanner/planner_test.go
Labels: bug

#144 [ISSUE-136] Fix typo in installation command in README.md
  docs/README.md
Labels: documentation

#148 [ISSUE-137] change curl flags
  Makefile.docker
Labels: bug
