Repository dell/csi-baremetal, pull requests merged in 2021-10, with the labels that each got.

#554 [ISSUE-551] Support proactive removal for OFFLINE drive
  pkg/crcontrollers/drive/drivecontroller.go
  pkg/node/volumemgr.go
  pkg/node/volumemgr_test.go
Labels: bug

#561 [ISSUE-558] Fix stucked AC after DR procedure
  .golangci.yml
  pkg/crcontrollers/drive/drivecontroller.go
Labels: bug

#560 [ISSUE-559] block device name change on node reboot causing fake attach
  .gitignore
  CODEOWNERS
  cmd/node/main.go
  pkg/node/node.go
  pkg/node/provisioners/drive_provisioner.go
Labels: bug

#563 [ISSUE-399] pod restart node id missing
  cmd/node/main.go
Labels: bug

#571 [ISSUE-553] Update crds baremetal
  .gitignore
  Makefile
  bin/.gitkeep
  docs/README.md
  docs/crds-generation.md
  go.mod
  go.sum
  variables.mk
Labels: enhancement

#576 [ISSUE-575] Run containers as user
  pkg/controller/Dockerfile
  pkg/crcontrollers/node/Dockerfile
  pkg/scheduler/extender/Dockerfile
Labels: enhancement, security

#568 [ISSUE-567] Release workflow
  .github/workflows/release.yml
  docs/images/release_workflow.png
  docs/release-workflow.md
Labels: enhancement

#580 [ISSUE-579] increase contribution guideline
  docs/CONTRIBUTING.md
Labels: documentation
