Repository dell/csi-baremetal, pull requests merged in 2021-06, with the labels that each got.

#419 [ISSUE-419] Change pull and tag centos image
  Makefile.validation
Labels: enhancement

#416 [ISSUE-415] Update version to 0.2.2
  charts/csi-baremetal-driver/Chart.yaml
  charts/csi-baremetal-operator/Chart.yaml
  charts/csi-baremetal-scheduler-extender/Chart.yaml
  charts/csi-baremetal-scheduler/Chart.yaml
  pkg/base/constants.go
  variables.mk
Labels: enhancement

#421 [ISSUE-420] Update volumes annotations on disk replacement
  pkg/crcontrollers/drive/drivecontroller.go
Labels: enhancement

#425 [ISSUE-424] Fake Attach Feature proposal
  docs/proposals/fake-attach.md
  docs/proposals/node-replacement.md
Labels: documentation

#428 [ISSUE-427] Check PVC fake-attach annotation on volume failed
  charts/csi-baremetal-driver/templates/node-rbac.yaml
  pkg/node/node.go
  pkg/node/volumemgr.go
Labels: enhancement

#432 [ISSUE-429] Invoke Fake Attach logic on NodeStage request
  docs/fake-attach.md
  pkg/mocks/provisioners/fs_operations.go
  pkg/node/node.go
  pkg/node/node_test.go
  pkg/node/provisioners/utilwrappers/fs_operations.go
Labels: enhancement

#433 [issue 426] handling ofline drive
  pkg/base/k8s/cr_helper.go
  pkg/crcontrollers/drive/drivecontroller.go
Labels: bug

#438 [ISSUE-437] Logs added for troubleshooting
  pkg/controller/controller.go
  pkg/scheduler/extender/extender.go
Labels: enhancement

#440 [ISSUE-439] Linter issue in statemonitor.go
  pkg/controller/node/statemonitor.go
Labels: bug

#443 [#442] Create status badge for PR validation
  docs/README.md
Labels: enhancement

#445 [ISSUE-441] Override Drive Health via annotation
  docs/proposals/drive-replacement.md
  pkg/eventing/eventing.go
  pkg/node/volumemgr.go
  pkg/node/volumemgr_test.go
  test/e2e/common/deploy.go
Labels: documentation, enhancement
