Repository dell/csi-baremetal, pull requests merged in 2021-12, with the labels that each got.

#584 [ISSUE-626] E2e testing in GitHub Actions
  .github/workflows/e2e.yml
  Makefile.validation
  test/kind/small-kind.yaml
  variables.mk
Labels: enhancement

#631 [ISSUE-626] e2e test on master
  .github/workflows/e2e.yml
  docs/README.md
Labels: documentation

#630 [ISSUE-625] Add mount options support
  docs/supported-mount-options.md
  pkg/base/linuxutils/fs/fs_helper.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/mountoptions/mount_options.go
  pkg/mocks/provisioners/fs_operations.go
  pkg/node/node.go
  pkg/node/provisioners/utilwrappers/fs_operations.go
  pkg/node/provisioners/utilwrappers/fs_operations_test.go
Labels: enhancement

#632 [ISSUE-626] e2e test skipped on master
  .github/workflows/e2e.yml
Labels: bug

#634 [ISSUE-633] Collect logs for every tests suite
  test/e2e/baremetal_e2e_test.go
  test/e2e/common/deploy.go
  test/e2e/reports/.gitkeep
Labels: enhancement

#628 [ISSUE-627] Switch CSI CI to K8s 1.19
  .github/workflows/e2e.yml
  variables.mk
Labels: enhancement

#640 [ISSUE-637] Support k8s 1.22 version for csi
  variables.mk
Labels: enhancement

#642 [ISSUE-641] upgrade kind to 0.11.1
  .github/workflows/e2e.yml
  variables.mk
Labels: enhancement

#655 [ISSUE-635] Support WBT disabling (release)
  cmd/node/main.go
  docs/custom-wbt-settings.md
  pkg/eventing/eventing.go
  pkg/mocks/executors.go
  pkg/mocks/linuxutils/wbt.go
  pkg/node/common_test_data.go
  pkg/node/node.go
  pkg/node/node_test.go
  pkg/node/volumemgr.go
  pkg/node/wbt/common/config.go
  pkg/node/wbt/operations/wbt_ops.go
  pkg/node/wbt/operations/wbt_ops_test.go
  pkg/node/wbt/wbt_watcher.go
Labels: enhancement

#648 [ISSUE-647] Upload artifacts to GH
  .github/workflows/e2e.yml
Labels: enhancement

#638 [ISSUE-635] Support WBT disabling
  cmd/node/main.go
  docs/custom-wbt-settings.md
  pkg/eventing/eventing.go
  pkg/mocks/executors.go
  pkg/mocks/linuxutils/wbt.go
  pkg/node/common_test_data.go
  pkg/node/node.go
  pkg/node/node_test.go
  pkg/node/volumemgr.go
  pkg/node/volumemgr_test.go
  pkg/node/wbt/common/config.go
  pkg/node/wbt/operations/wbt_ops.go
  pkg/node/wbt/operations/wbt_ops_test.go
  pkg/node/wbt/wbt_watcher.go
  test/kind/kind.yaml
Labels: enhancement

#652 [ISSUE-651] Immediate volume binding mode proposal
  docs/README.md
  docs/proposals/immediate-volume-binding-mode.md
Labels: documentation

#657 [ISSUE-656] Support SLES 15 SP3 in CSI
  .github/.codecov.yaml
  docs/kernel-distribution-dependenant-tools.md
  pkg/base/linuxutils/partitionhelper/partition_helper.go
  pkg/base/linuxutils/partitionhelper/partitionhelper_test.go
  pkg/mocks/commands.go
  pkg/mocks/linuxutils/partitionhelper.go
  pkg/node/Dockerfile.build
  pkg/node/provisioners/utilwrappers/partition_operations.go
  pkg/node/provisioners/utilwrappers/parttiion_operations_test.go
Labels: enhancement

#609 [ISSUE-298] Enable volume expansion tests
  pkg/node/Dockerfile-kernel-5.4.build
  pkg/node/Dockerfile.build
  test/e2e/scenarios/bare-metal-testdriver.go
  test/e2e/scenarios/controller-node-fail.go
  test/e2e/scenarios/setup.go
  test/kind/kind.yaml
Labels: enhancement

#663 [ISSUE-662] Controller creates ACs with ANY SC instead of SYSLVG
  pkg/controller/capacitycontroller/capacitycontroller.go
  pkg/controller/capacitycontroller/capacitycontroller_test.go
Labels: bug

#645 [ISSUE-644] Support non default CSI deployment at Openshift platform
  docs/proposals/non-default-namespace-deployment.md
Labels: documentation

#646 [ISSUE-123] Pre-provisioned volumes documentation
  Makefile.validation
  docs/pre-provisioned-volumes.md
  test/e2e/scenarios/bare-metal-testdriver.go
Labels: documentation

#667 [ISSUE-656]: fix partition alignment
  pkg/base/linuxutils/partitionhelper/partition_helper.go
  pkg/mocks/commands.go
Labels: bug

#670 [ISSUE-647] e2e test artifacts
  .github/workflows/e2e.yml
Labels: bug

#672 [ISSUE-671] Fix vulnerability issue in GitHub e2e workflow
  .github/workflows/e2e.yml
Labels: bug

#675 [ISSUE-671] Fix Github e2e workflow
  .github/workflows/e2e.yml
Labels: bug

#674 [ISSUE-647] e2e test artifacts
  .github/workflows/e2e.yml
  docs/README.md
Labels: bug

#680 [ISSUE-679]: Don't skip drives with UNKNOWN health
  pkg/controller/capacitycontroller/capacitycontroller.go
  pkg/controller/capacitycontroller/capacitycontroller_test.go
Labels: enhancement

#681 [ISSUE-647] e2e workflow
  .github/workflows/e2e.yml
Labels: enhancement

#678 [ISSUE-677]: Proposal for CSI volume health feature support
  docs/proposals/volume-health-monitoring.md
Labels: documentation, enhancement
