Repository dell/csi-baremetal, pull requests merged in 2021-09, with the labels that each got.

#506 [ISSUE-505] Update alpine version to 3.14
  pkg/controller/Dockerfile.build
  pkg/crcontrollers/operator/Dockerfile
  pkg/crcontrollers/operator/controller.go
  pkg/node/Dockerfile-kernel-5.4.build
  pkg/node/Dockerfile.build
  pkg/scheduler/extender/Dockerfile
  pkg/scheduler/patcher/Dockerfile
  pkg/scheduler/plugin/Dockerfile
Labels: enhancement

#504 [ISSUE-503] Validating webhook proposal
  docs/proposals/csi-webhook.md
Labels: enhancement

#508 [ISSUE-507] Update Ubuntu version to 21.04
  pkg/drivemgr/basemgr/Dockerfile.build
  pkg/drivemgr/loopbackmgr/Dockerfile.build
  pkg/node/Dockerfile-kernel-5.4.build
  pkg/node/Dockerfile.build
Labels: security

#510 [ISSUE-509] Add verbose kubectl output for LVG and ACR
  api/v1/acreservationcrd/availablecapacityreservation_types.go
  api/v1/lvgcrd/logicalvolumegroup_types.go
  charts/csi-baremetal-driver/crds/csi-baremetal.dell.com_availablecapacityreservations.yaml
  charts/csi-baremetal-driver/crds/csi-baremetal.dell.com_logicalvolumegroups.yaml
Labels: enhancement

#516 [ISSUE-515] Rename node operator image
  Makefile
  Makefile.docker
  Makefile.validation
  cmd/drivemgr/loopbackmgr/main.go
  cmd/node-controller/main.go
  cmd/node/main.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/crcontrollers/node/Dockerfile
  pkg/crcontrollers/node/common/annotation.go
  pkg/crcontrollers/node/common/annotation_test.go
  pkg/crcontrollers/node/common/const.go
  pkg/crcontrollers/node/controller.go
  pkg/crcontrollers/node/controller_test.go
  pkg/node/node.go
  pkg/node/node_test.go
  pkg/scheduler/extender/extender.go
  pkg/scheduler/extender/extender_test.go
  test/e2e/scenarios/drive-health-change.go
  variables.mk
Labels: enhancement

#517 [ISSUE-515] Fix CSI Operator pull target
  variables.mk
Labels: bug

#519 [ISSUE-518] DriveRemovalFailed event isn't generated after volume release=failed
  api/v1/drivecrd/drive_types.go
  pkg/node/volumemgr.go
Labels: bug

#513 [ISSUE-512] Move TopologyID labels deletion into Operator
  pkg/crcontrollers/node/controller.go
Labels: bug

#514 [ISSUE-511] Fix restoring the same node after removal
  docs/node-removal.md
  docs/proposals/automated-node-removal.md
  pkg/crcontrollers/node/controller.go
  pkg/crcontrollers/node/controller_test.go
Labels: bug

#523 [ISSUE-522] Node reboot test failed in CI
  test/e2e/scenarios/node-reboot.go
Labels: bug

#527 [ISSUE-524] Disable node location after disk removal
  api/generated/v1/drivemgrsvc.pb.go
  api/v1/drivemgrsvc.proto
  pkg/crcontrollers/drive/drivecontroller.go
  pkg/drivemgr/basemgr/basemgr.go
  pkg/drivemgr/drivemgr.go
  pkg/drivemgr/drivemgr_service.go
  pkg/drivemgr/idracmgr/idracmgr.go
  pkg/drivemgr/loopbackmgr/loopbackmgr.go
  pkg/mocks/drivemgr.go
Labels: bug

#531 [ISSUE-500] Fix CI issue caused by parameter change
  test/e2e/common/deploy.go
Labels: bug

#532 [ISSUE-529] Fix csi-controller restart after node removal
  pkg/controller/node/statemonitor.go
Labels: bug

#530 [ISSUE-526] Bump CSI version to 0.5.0
  charts/csi-baremetal-driver/Chart.yaml
  charts/csi-baremetal-operator/Chart.yaml
  charts/csi-baremetal-scheduler-extender/Chart.yaml
  charts/csi-baremetal-scheduler/Chart.yaml
  pkg/base/constants.go
  variables.mk
Labels: enhancement

#534 [ISSUE-533] Add app labels to custom resources
  pkg/base/k8s/kubeclient.go
Labels: bug

#537 [ISSUE-536] Change event wording
  pkg/crcontrollers/drive/drivecontroller.go
Labels: enhancement

#541 [ISSUE-540] Fix node_capacity log message
  pkg/base/capacityplanner/node_capacity.go
Labels: bug

#542 [ISSUE-539] skip SN check
  .golangci.yml
  pkg/base/linuxutils/datadiscover/datadiscover.go
  pkg/base/linuxutils/datadiscover/datadiscover_test.go
  pkg/base/linuxutils/partitionhelper/partition_helper.go
  pkg/base/linuxutils/partitionhelper/partitionhelper_test.go
  pkg/mocks/linuxutils/partitionhelper.go
Labels: bug

#543 [ISSUE-538] Update node-driver-registrar sidecar
  Makefile.validation
  variables.mk
Labels: enhancement

#547 [ISSUE-544] code owners added
  docs/CODEOWNERS
Labels: documentation

#549 [ISSUE-548] Idempotent PrepareVolume procedure
  pkg/base/linuxutils/datadiscover/datadiscover.go
  pkg/base/linuxutils/datadiscover/datadiscover_test.go
  pkg/base/linuxutils/fs/fs_helper.go
  pkg/base/linuxutils/fs/fs_helper_test.go
  pkg/mocks/linuxutils/fs_helper.go
  pkg/mocks/provisioners/fs_operations.go
  pkg/node/provisioners/drive_provisioner.go
  pkg/node/provisioners/drive_provisioner_test.go
  pkg/node/provisioners/lvm_provisioner.go
  pkg/node/provisioners/lvm_provisioner_test.go
  pkg/node/provisioners/utilwrappers/fs_operations.go
  pkg/node/provisioners/utilwrappers/fs_operations_test.go
  pkg/node/provisioners/utilwrappers/partition_operations.go
  pkg/node/provisioners/utilwrappers/parttiion_operations_test.go
  pkg/node/volumemgr.go
Labels: bug
