Repository dell/csi-baremetal, pull requests merged in 2021-05, with the labels that each got.

#384 [ISSUE-382] Labels for the logging and crashdump folder
  charts/csi-baremetal-driver/templates/controller.yaml
  charts/csi-baremetal-driver/templates/node.yaml
  charts/csi-baremetal-operator/templates/csibm-controller.yaml
  charts/csi-baremetal-scheduler-extender/templates/patcher.yaml
  charts/csi-baremetal-scheduler-extender/templates/scheduler-extender.yaml
  charts/csi-baremetal-scheduler/templates/scheduler.yaml
Labels: enhancement

#386 [ISSUE-370] Reserve resources on requested nodes only
  pkg/base/capacityplanner/mocks.go
  pkg/base/capacityplanner/planner.go
  pkg/base/capacityplanner/planner_test.go
  pkg/scheduler/extender/extender.go
Labels: enhancement

#392 [ISSUE-391] Fix centos container image pull rate limit
  Makefile.validation
  test/e2e/common/pod.go
Labels: bug

#365 [ISSUE-364] Implement controller for drive and lvg and refactor discoverVolumeCRs
  api/generated/v1/types.pb.go
  api/v1/constants.go
  api/v1/types.proto
  charts/csi-baremetal-driver/crds/csi-baremetal.dell.com_drives.yaml
  cmd/controller/main.go
  docs/proposals/ac-refactoring.md
  pkg/base/capacityplanner/planner_test.go
  pkg/base/linuxutils/datadiscover/datadiscover.go
  pkg/base/linuxutils/datadiscover/datadiscover_test.go
  pkg/base/linuxutils/datadiscover/types/types.go
  pkg/base/linuxutils/fs/fs_helper.go
  pkg/base/linuxutils/fs/fs_helper_test.go
  pkg/base/linuxutils/lvm/lvm.go
  pkg/base/linuxutils/partitionhelper/partition_helper.go
  pkg/base/linuxutils/partitionhelper/partitionhelper_test.go
  pkg/controller/capacitycontroller/capacitycontroller.go
  pkg/controller/capacitycontroller/capacitycontroller_test.go
  pkg/controller/controller.go
  pkg/crcontrollers/lvg/lvgcontroller.go
  pkg/crcontrollers/lvg/lvgcontroller_test.go
  pkg/eventing/eventing.go
  pkg/mocks/linuxutils/datadiscover.go
  pkg/mocks/linuxutils/fs_helper.go
  pkg/mocks/linuxutils/partitionhelper.go
  pkg/node/common_test_data.go
  pkg/node/volumemgr.go
  pkg/node/volumemgr_test.go
  pkg/scheduler/extender/extender_test.go
  test/e2e/scenarios/drive-health-change.go
  test/e2e/scenarios/node-labels.go
  test/sanity/sanity_test.go
Labels: documentation, enhancement

#394 [ ISSUE-390] Extender creates acr after volumes has been already created
  pkg/scheduler/extender/extender.go
Labels: bug

#383 [ISSUE-379] Integrate e2e tests with CSI Operator
  Makefile.validation
  test/e2e/baremetal_e2e_test.go
  test/e2e/common/deploy-plugin-components.go
  test/e2e/common/deploy.go
  test/e2e/common/helm.go
  test/e2e/common/pod.go
  test/e2e/common/scheduler-restart.go
  test/e2e/common/testcontext.go
  test/e2e/scenarios/bare-metal-testdriver.go
  test/e2e/scenarios/different-sc-test.go
  test/e2e/scenarios/drive-health-change.go
  test/e2e/scenarios/node-labels.go
  test/e2e/scenarios/scheduler-test.go
  test/e2e/scenarios/setup.go
Labels: enhancement

#398 [ISSUE-397] Fix typo in LVGs CRD
  api/v1/lvgcrd/logicalvolumegroup_types.go
  charts/csi-baremetal-driver/crds/csi-baremetal.dell.com_logicalvolumegroups.yaml
Labels: bug

#404 [ISSUE-403] Remove outdated flags from csi-operator chart
  charts/csi-baremetal-operator/templates/csibm-controller.yaml
Labels: bug

#401 [ISSUE-400] Node label test must wait csi reconciliation
  test/e2e/common/deploy.go
  test/e2e/scenarios/node-labels.go
Labels: bug

#408 [ISSUE-407] Improve e2e testing due to issues found with CI
  test/e2e/common/deploy.go
  test/e2e/scenarios/bare-metal-testdriver.go
  test/e2e/scenarios/node-labels.go
  test/e2e/scenarios/setup.go
Labels: bug
