Repository dell/csi-baremetal, pull requests merged in 2021-08, with the labels that each got.

#472 [ISSUE-463] ignore not found pvc and retry it
  pkg/scheduler/extender/extender.go
  pkg/scheduler/extender/extender_test.go
Labels: bug

#465 [ISSUE-464] Scheduler-extender readiness check
  Makefile.docker
  cmd/scheduling/extender/main.go
  docs/proposals/extender-readiness-check.md
  docs/proposals/images/Operator_Openshift_deletion-handle.png
  docs/proposals/images/Operator_openshift_flow.png
  docs/proposals/images/Operator_vanilla_deletion-handle.png
  docs/proposals/images/Operator_vanilla_flow.png
  docs/proposals/images/Patcher_SIGTERM_flow.png
  docs/proposals/images/Patcher_flow.png
  docs/proposals/images/extender_flow.png
  pkg/scheduler/extender/Dockerfile
  pkg/scheduler/extender/healthserver/common/common.go
  pkg/scheduler/extender/healthserver/health_server.go
  pkg/scheduler/extender/healthserver/health_server_test.go
  pkg/scheduler/patcher/main.py
  pkg/scheduler/patcher/requirements.txt
  test/e2e/common/deploy.go
  test/e2e/scenarios/bare-metal-testdriver.go
Labels: enhancement

#478 [ISSUE-464] Retry patching after kube-scheduler not restarted
  test/e2e/common/deploy.go
Labels: bug

#482 [ISSUE-463] Retry on PVC not found
  pkg/scheduler/extender/extender.go
  pkg/scheduler/extender/extender_test.go
Labels: bug

#484 [ISSUE-483] Race condition between Extender and Controller on disk replacement
  pkg/common/volume_operations.go
Labels: bug

#491 Set version 0.4.0
  .github/workflows/pr.yml
  charts/csi-baremetal-driver/Chart.yaml
  charts/csi-baremetal-operator/Chart.yaml
  charts/csi-baremetal-scheduler-extender/Chart.yaml
  charts/csi-baremetal-scheduler/Chart.yaml
  pkg/base/constants.go
  variables.mk
Labels: enhancement

#490 [ISSUE-489] re-activate volume group on disk reinsert
  pkg/base/linuxutils/lvm/lvm.go
  pkg/base/linuxutils/lvm/lvm_test.go
  pkg/eventing/eventing.go
  pkg/mocks/linuxutils/lvm.go
  pkg/node/volumemgr.go
  pkg/node/volumemgr_test.go
Labels: bug

#499 [ISSUE-498] Add Symptom Codes for CSI events
  api/v1/constants.go
  cmd/node/main.go
  pkg/base/linuxutils/lvm/lvm_test.go
  pkg/crcontrollers/drive/drivecontroller.go
  pkg/eventing/event_manager.go
  pkg/eventing/eventing.go
  pkg/events/doc.go
  pkg/events/events.go
  pkg/events/events_test.go
  pkg/events/example_test.go
  pkg/mocks/events.go
  pkg/node/node.go
  pkg/node/volumemgr.go
  pkg/node/volumemgr_test.go
  test/e2e/scenarios/drive-health-change.go
Labels: enhancement

#493 [ISSUE-492] Manipulate Drive Usage via annotations
  docs/proposals/drive-replacement.md
  pkg/controller/capacitycontroller/capacitycontroller.go
  pkg/controller/capacitycontroller/capacitycontroller_test.go
  pkg/crcontrollers/drive/drivecontroller.go
Labels: documentation, enhancement

#502 [ISSUE-501] Update README
  docs/README.md
Labels: documentation
