Repository dell/csi-baremetal, pull requests merged in 2021-03, with the labels that each got.

#301 [ISSUE-134] Fix issue with loopback devices cleanup
  docs/CONTRIBUTING.md
  docs/README.md
  docs/proposals/node_replacement.md
  test/e2e/scenarios/bare-metal-testdriver.go
  test/e2e/scenarios/controller-node-fail.go
  test/e2e/scenarios/drive-health-change.go
  test/e2e/scenarios/node-reboot.go
  test/e2e/scenarios/stress-test.go
Labels: bug

#279 [ISSUE-296] Volume expansion implementation
  Makefile.validation
  api/v1/constants.go
  charts/csi-baremetal-driver/templates/controller-rbac.yaml
  charts/csi-baremetal-driver/templates/controller.yaml
  charts/csi-baremetal-driver/templates/hddlvg-sc.yaml
  charts/csi-baremetal-driver/templates/ssdlvg-sc.yaml
  charts/csi-baremetal-driver/templates/syslvg-sc.yaml
  charts/csi-baremetal-driver/values.yaml
  pkg/base/k8s/cr_helper.go
  pkg/base/k8s/cr_helper_test.go
  pkg/base/linuxutils/lsblk/lsblk_test.go
  pkg/base/linuxutils/lvm/lvm.go
  pkg/common/volume_operations.go
  pkg/common/volume_operations_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/identity.go
  pkg/mocks/linuxutils/lvm.go
  pkg/mocks/volume_operations.go
  pkg/node/node.go
  pkg/node/volumemgr.go
  pkg/node/volumemgr_test.go
  variables.mk
Labels: enhancement

#304 [ISSUE-303] CSI Operator must put kernel version label on the node
  pkg/base/util/parser.go
  pkg/base/util/parser_test.go
  pkg/crcontrollers/operator/common/const.go
  pkg/crcontrollers/operator/controller.go
  pkg/crcontrollers/operator/controller_test.go
Labels: enhancement

#311 [ISSUE-308] kernel version choice
  Makefile.docker
  Makefile.validation
  charts/csi-baremetal-driver/templates/node.yaml
  charts/csi-baremetal-driver/values.yaml
  pkg/base/util/parser.go
  pkg/base/util/parser_test.go
  pkg/crcontrollers/operator/controller_test.go
  pkg/node/Dockerfile-kernel-5.4
  pkg/node/Dockerfile-kernel-5.4.build
  test/app/nginx.yaml
Labels: enhancement

#306 [ISSUE-305] Label Management Proposal
  docs/proposals/label-management.md
Labels: bug, documentation

#309 [ISSUE-307] Prepare CRD for CSI deployment
  docs/proposals/csi-deployment-crd.md
Labels: documentation

#315 [ISSUE-312] Add deployment based on os kernel version
  api/v1/constants.go
  cmd/operator/main.go
  pkg/common/installer.go
  pkg/common/installer_test.go
  pkg/crcontrollers/operator/controller.go
  pkg/crcontrollers/operator/controller_test.go
Labels: enhancement

#314 [ISSUE-313] Add external annotations support
  charts/csi-baremetal-driver/templates/node.yaml
  charts/csi-baremetal-driver/values.yaml
  charts/csi-baremetal-operator/templates/csibm-controller.yaml
  charts/csi-baremetal-operator/values.yaml
  charts/csi-baremetal-scheduler-extender/templates/scheduler-extender.yaml
  charts/csi-baremetal-scheduler-extender/values.yaml
  cmd/drivemgr/loopbackmgr/main.go
  cmd/node/main.go
  cmd/operator/main.go
  cmd/scheduling/extender/main.go
  docs/proposals/label-management.md
  pkg/base/featureconfig/feature.go
  pkg/base/k8s/kubeclient.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/crcontrollers/operator/common/annotation.go
  pkg/crcontrollers/operator/common/annotation_test.go
  pkg/crcontrollers/operator/common/const.go
  pkg/crcontrollers/operator/controller.go
  pkg/crcontrollers/operator/controller_test.go
  pkg/node/node.go
  pkg/node/node_test.go
  pkg/scheduler/extender/extender.go
  pkg/scheduler/extender/extender_test.go
  test/e2e/common/deploy-plugin-components.go
  test/e2e/scenarios/drive-health-change.go
Labels: bug

#321 [ISSUE-320] Fix sanity testing
  Makefile.validation
  pkg/mocks/linuxutils/lsblk.go
  pkg/node/volumemgr.go
  test/sanity/sanity_test.go
Labels: bug

#325 [ISSUE-322] Add e2e tests for deployment with node labels
  test/e2e/scenarios/node-labels.go
  test/e2e/scenarios/setup.go
Labels: enhancement

#324 [ISSUE-323] Documents node remove
  charts/csi-baremetal-driver/crds/csi-baremetal.dell.com_availablecapacities.yaml
  charts/csi-baremetal-driver/crds/csi-baremetal.dell.com_availablecapacityreservations.yaml
  charts/csi-baremetal-driver/crds/csi-baremetal.dell.com_drives.yaml
  charts/csi-baremetal-driver/crds/csi-baremetal.dell.com_logicalvolumegroups.yaml
  charts/csi-baremetal-driver/crds/csi-baremetal.dell.com_volumes.yaml
  charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_nodes.yaml
  docs/node-removal.md
Labels: documentation

#327 [ISSUE-326] Add debug logging in PrepareAndPerformMount
  pkg/node/provisioners/utilwrappers/fs_operations.go
  pkg/node/provisioners/utilwrappers/fs_operations_test.go
Labels: bug

#331 CSI beta release
  charts/csi-baremetal-driver/values.yaml
  charts/csi-baremetal-operator/values.yaml
  charts/csi-baremetal-scheduler-extender/values.yaml
  charts/csi-baremetal-scheduler/values.yaml
  docs/README.md
  pkg/scheduler/patcher/openshift_patcher.sh
Labels: documentation, enhancement

#335 Add image pull secret
  charts/csi-baremetal-driver/templates/controller.yaml
  charts/csi-baremetal-driver/templates/node.yaml
  charts/csi-baremetal-driver/values.yaml
  charts/csi-baremetal-operator/templates/csibm-controller.yaml
  charts/csi-baremetal-operator/values.yaml
  charts/csi-baremetal-scheduler-extender/templates/scheduler-extender.yaml
  charts/csi-baremetal-scheduler-extender/values.yaml
  charts/csi-baremetal-scheduler/templates/scheduler.yaml
  charts/csi-baremetal-scheduler/values.yaml
  docs/README.md
Labels: documentation, enhancement

#346 [ISSUE-342] Add kubebuilder markers for column generation
  api/v1/acreservationcrd/availablecapacityreservation_types.go
  api/v1/availablecapacitycrd/availablecapacity_types.go
  api/v1/drivecrd/drive_types.go
  api/v1/lvgcrd/logicalvolumegroup_types.go
  api/v1/nodecrd/node_types.go
  api/v1/volumecrd/volume_types.go
  charts/csi-baremetal-driver/crds/csi-baremetal.dell.com_availablecapacities.yaml
  charts/csi-baremetal-driver/crds/csi-baremetal.dell.com_availablecapacityreservations.yaml
  charts/csi-baremetal-driver/crds/csi-baremetal.dell.com_drives.yaml
  charts/csi-baremetal-driver/crds/csi-baremetal.dell.com_logicalvolumegroups.yaml
  charts/csi-baremetal-driver/crds/csi-baremetal.dell.com_volumes.yaml
  charts/csi-baremetal-operator/crds/csi-baremetal.dell.com_nodes.yaml
Labels: enhancement
