Repository dell/csi-baremetal, pull requests merged in 2021-07, with the labels that each got.

#451 [ISSUE-450] Build custom kind for CI
  Makefile.validation
  test/kind/kind.patch
  test/kind/kind.yaml
  variables.mk
Labels: enhancement

#448 [ISSUE-447] Repeat Drive Replacement procedure
  docs/proposals/drive-replacement.md
  pkg/crcontrollers/drive/drivecontroller.go
Labels: documentation, enhancement

#457 [ISSUE-456] Downgrade kind version to 0.8.1
  Makefile.validation
  test/kind/kind-0.11.1.patch
  test/kind/kind-0.8.1.patch
  test/kind/kind.yaml
  variables.mk
Labels: bug

#435 [ISSUE-434] Automated node removal Proposal
  docs/proposals/automated-node-removal.md
Labels: enhancement

#460 [ISSUE-459] Integration with codecov.io
  .github/workflows/pr.yml
  Makefile.validation
  docs/README.md
Labels: enhancement

#462 Update version to 0.3.0
  charts/csi-baremetal-driver/Chart.yaml
  charts/csi-baremetal-operator/Chart.yaml
  charts/csi-baremetal-scheduler-extender/Chart.yaml
  charts/csi-baremetal-scheduler/Chart.yaml
  pkg/base/constants.go
  variables.mk
Labels: enhancement

#468 [ISSUE-467] Fix drive health overriding
  pkg/node/volumemgr.go
Labels: bug
