Repository dell/csi-baremetal, pull requests merged in 2021-11, with the labels that each got.

#593 [ISSUE-592] Skip for non-community tests
  Makefile.validation
  test/kind/kind.yaml
Labels: enhancement

#597 [ISSUE-596] Extend Locate statuses with N/A
  api/v1/constants.go
  pkg/crcontrollers/drive/drivecontroller.go
Labels: bug

#607 [ISSUE-606] Update CSI version to 1.1.0
  pkg/base/constants.go
  variables.mk
Labels: documentation

#605 [ISSUE-604] Proposal CSI Baremetal CI on Github Actions
  docs/proposals/ci-in-github-action.md
Labels: documentation

#610 [ISSUE-608] Skip block volume tests in short CI suite
  Makefile.validation
  test/e2e/baremetal_e2e_test.go
  test/e2e/common/testcontext.go
  test/e2e/scenarios/bare-metal-testdriver.go
  test/e2e/scenarios/controller-node-fail.go
  test/e2e/scenarios/different-sc-test.go
  test/e2e/scenarios/drive-health-change.go
  test/e2e/scenarios/node-labels.go
  test/e2e/scenarios/node-reboot.go
  test/e2e/scenarios/scheduler-test.go
  test/e2e/scenarios/setup.go
  test/e2e/scenarios/stress-test.go
Labels: enhancement

#621 [ISSUE-620] PR template updated to use projects
  docs/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#615 [ISSUE-614] Add timeout for test-short-ci suite
  Makefile.validation
  test/e2e/baremetal_e2e_test.go
  test/e2e/common/testcontext.go
  test/e2e/scenarios/setup.go
  test/kind/kind.yaml
  variables.mk
Labels: enhancement

#619 [ISSUE-616] block pr merge when UTs code coverage decreased
  .github/workflows/pr.yml
Labels: enhancement

#623 [ISSUE-622] Improve logging in scheduler-extender
  pkg/scheduler/extender/extender.go
  pkg/scheduler/extender/extender_test.go
Labels: enhancement
