Repository dell/csi-baremetal, pull requests merged in 2021-02, with the labels that each got.

#257 [ISSUE-251] Expose duration of kube-client methods
  pkg/base/k8s/kubeclient.go
  pkg/metrics/common/kubeclient.go
Labels: enhancement

#258 [ALT-1501] Temporary reserve LVG AC after creation
  pkg/base/capacityplanner/helpers.go
  pkg/base/capacityplanner/helpers_test.go
  pkg/common/ac_operations.go
  pkg/common/ac_operations_test.go
  pkg/common/volume_operations.go
  pkg/common/volume_operations_test.go
  pkg/mocks/ac_operatrions.go
Labels: bug

#261 [ISSUE-259] non zero ac for system disk
  pkg/node/volumemgr.go
Labels: bug

#263 [ISSUE-262] loopbackmgr system drive error
  pkg/base/constants.go
  pkg/common/volume_operations.go
  pkg/crcontrollers/lvg/lvgcontroller.go
  pkg/node/volumemgr.go
  pkg/node/volumemgr_test.go
Labels: bug

#267 [ISSUE-265] Trace level cause crash in the extender
  pkg/scheduler/patcher/main.py
Labels: bug

#266 [ISSUE-264] Change version to 0.0.13
  charts/baremetal-csi-plugin/Chart.yaml
  charts/csibm-operator/Chart.yaml
  charts/scheduler-extender/Chart.yaml
  charts/scheduler/Chart.yaml
  pkg/base/constants.go
  variables.mk
Labels: enhancement

#253 [ISSUE-252] Expose duration of the different system utils
  cmd/drivemgr/basemgr/main.go
  cmd/drivemgr/idracmgr/main.go
  cmd/drivemgr/loopbackmgr/main.go
  pkg/base/command/cmdexec.go
  pkg/base/command/cmdexec_test.go
  pkg/base/linuxutils/fs/fs_helper.go
  pkg/base/linuxutils/ipmi/ipmitool.go
  pkg/base/linuxutils/lsblk/lsblk.go
  pkg/base/linuxutils/lsscsi/lsscsi.go
  pkg/base/linuxutils/lvm/lvm.go
  pkg/base/linuxutils/nvmecli/nvmecli.go
  pkg/base/linuxutils/partitionhelper/partition_helper.go
  pkg/base/linuxutils/smartctl/smartctl.go
  pkg/crcontrollers/lvg/lvgcontroller.go
  pkg/drivemgr/loopbackmgr/loopbackmgr.go
  pkg/metrics/common/sysutil.go
  pkg/mocks/executors.go
  pkg/node/node.go
  test/e2e/common/util.go
  test/e2e/scenarios/controller-node-fail.go
  test/e2e/scenarios/node-reboot.go
Labels: enhancement

#273 [ISSUE-272] Add mount for csi staging path to node POD
  charts/baremetal-csi-plugin/templates/baremetal-csi-node.yaml
Labels: bug

#276 [ISSUE-275] Add PR validation with GH actions
  .github/workflows/pr.yml
  test/e2e/baremetal_e2e_test.go
Labels: enhancement

#281 [ISSUE-280] Fix AvailableCapacity size computation for LVM
  pkg/base/capacityplanner/common.go
  pkg/base/capacityplanner/common_test.go
  pkg/base/capacityplanner/node_capacity.go
  pkg/base/capacityplanner/planner_test.go
  pkg/common/ac_operations.go
  pkg/common/ac_operations_test.go
Labels: bug

#287 [ISSUE-177] Add generated files to the repository
  .github/workflows/pr.yml
  .gitignore
  Makefile
  api/generated/v1/drivemgrsvc.pb.go
  api/generated/v1/types.pb.go
  api/v1/acreservationcrd/zz_generated.deepcopy.go
  api/v1/availablecapacitycrd/zz_generated.deepcopy.go
  api/v1/csibmnodecrd/zz_generated.deepcopy.go
  api/v1/drivecrd/zz_generated.deepcopy.go
  api/v1/lvgcrd/zz_generated.deepcopy.go
  api/v1/volumecrd/zz_generated.deepcopy.go
Labels: enhancement

#286 [ISSUE-285] Fix detection of updated node labels
  pkg/crcontrollers/csibmnode/controller.go
Labels: bug

#284 Update Go version
  .github/workflows/pr.yml
Labels: enhancement

#274 [ISSUE-269] Use CR caching in csi-node Discover loop
  cmd/node/main.go
  pkg/base/k8s/cr_helper.go
  pkg/base/k8s/kubecache.go
  pkg/base/k8s/kubeclient.go
  pkg/node/node.go
  pkg/node/node_test.go
  pkg/node/volumemgr.go
  pkg/node/volumemgr_test.go
  test/sanity/sanity_test.go
Labels: enhancement

#277 [ISSUE-269] Add caching support to scheduler extender
  charts/scheduler-extender/templates/rbac.yaml
  cmd/node/main.go
  cmd/scheduling/extender/main.go
  pkg/base/k8s/kubecache.go
  pkg/scheduler/extender/extender.go
  pkg/scheduler/extender/extender_test.go
Labels: enhancement

#291 [ISSUE-282] lsblk v2 support
  pkg/base/linuxutils/lsblk/lsblk.go
  pkg/base/linuxutils/lsblk/lsblk_test.go
  pkg/mocks/commands.go
  pkg/node/volumemgr.go
  pkg/node/volumemgr_test.go
Labels: enhancement

#271 [ISSUE-268] Volume expansion proposal
  docs/proposals/volume-expansion.md
Labels: documentation, enhancement

#163 [ISSUE-292] RAW Block volumes support
  pkg/base/linuxutils/fs/fs_helper.go
  pkg/controller/controller.go
  pkg/mocks/linuxutils/fs_helper.go
  pkg/mocks/provisioners/fs_operations.go
  pkg/node/node.go
  pkg/node/node_test.go
  pkg/node/provisioners/drive_provisioner.go
  pkg/node/provisioners/lvm_provisioner.go
  pkg/node/provisioners/utilwrappers/fs_operations.go
  pkg/node/provisioners/utilwrappers/fs_operations_test.go
  test/e2e/common/pod.go
  test/e2e/scenarios/controller-node-fail.go
  test/e2e/scenarios/different-sc-test.go
  test/e2e/scenarios/drive-health-change.go
  test/e2e/scenarios/node-reboot.go
  test/sanity/sanity_test.go
Labels: enhancement

#294 [ISSUE-293] capacityplanner.selectACForVolume function refactoring
  pkg/base/capacityplanner/node_capacity.go
Labels: enhancement

#295 [ISSUE-289] update golangci-lint version
  .github/workflows/pr.yml
Labels: chore
