Repository dell/csi-baremetal, pull requests merged in 2021-04, with the labels that each got.

#354 [ISSUE-353] Fix node removal docs
  docs/node-removal.md
Labels: chore

#358 [ISSUE-357] update csi docs to reflect current project status
  charts/csi-baremetal-scheduler-extender/values.yaml
  docs/README.md
Labels: documentation

#369 [ISSUE-437] CSI support for the 1.19 K8S
  charts/csi-baremetal-scheduler-extender/templates/patcher-configmap.yaml
  charts/csi-baremetal-scheduler-extender/templates/patcher.yaml
  charts/csi-baremetal-scheduler-extender/values.yaml
  pkg/scheduler/patcher/config.yaml
  pkg/scheduler/patcher/main.py
  pkg/scheduler/patcher/policy.yaml
  pkg/scheduler/patcher/requirements.txt
Labels: enhancement

#378 [ISSUE-377] Update version to 0.2.0
  charts/csi-baremetal-driver/Chart.yaml
  charts/csi-baremetal-operator/Chart.yaml
  charts/csi-baremetal-scheduler-extender/Chart.yaml
  charts/csi-baremetal-scheduler/Chart.yaml
  pkg/base/constants.go
  variables.mk
Labels: enhancement

#376 [ISSUE-375] Release reservation when volume creation stuck or failed
  pkg/base/capacityplanner/helpers.go
  pkg/base/capacityplanner/helpers_test.go
  pkg/base/capacityplanner/mocks.go
  pkg/common/volume_operations.go
  pkg/crcontrollers/reservation/reservationcontroller.go
  pkg/scheduler/extender/extender.go
Labels: bug

#374 [ISSUE-373] CSI support for rke2r1
  charts/csi-baremetal-scheduler-extender/templates/patcher-configmap.yaml
  charts/csi-baremetal-scheduler-extender/templates/patcher.yaml
  charts/csi-baremetal-scheduler-extender/values.yaml
  pkg/scheduler/patcher/main.py
Labels: enhancement
