Repository dell/csi-baremetal, pull requests merged in 2021-01, with the labels that each got.

#190 [Issue-138] Issue Template creation
  docs/issue_template.md
Labels: documentation

#230 [ISSUE-228] Add annotations for the metrics discovery
  charts/baremetal-csi-plugin/templates/baremetal-csi-controller.yaml
  charts/baremetal-csi-plugin/templates/baremetal-csi-node.yaml
  charts/baremetal-csi-plugin/values.yaml
  cmd/controller/main.go
  cmd/node/main.go
Labels: enhancement

#229 [ISSUE-88] Handle disk health change for lvg volumes
  api/v1/types.proto
  pkg/base/k8s/cr_helper.go
  pkg/common/ac_operations.go
  pkg/crcontrollers/lvg/lvgcontroller.go
  pkg/crcontrollers/lvg/lvgcontroller_test.go
  pkg/node/volumemgr.go
  pkg/node/volumemgr_test.go
Labels: bug

#233 [ISSUE-232] Don't use LVG for volumes with ANY storage type
  api/v1/constants.go
  charts/baremetal-csi-plugin/templates/baremetal-csi-sc.yaml
  pkg/base/capacityplanner/node_capacity.go
  pkg/base/capacityplanner/planner_test.go
  pkg/scheduler/extender/extender_test.go
  pkg/scheduler/patcher/main.py
  test/e2e/common/deploy-plugin-components.go
Labels: bug

#237 [ISSUE-86] Handle owner addition/deletion during node publish/unpublish
  pkg/node/node.go
  pkg/node/node_test.go
Labels: bug

#234 [ISSUE-222] Volume cr must be created in the same namespace as pvc/pv
  charts/baremetal-csi-plugin/crds/baremetal-csi.dellemc.com_volumes.yaml
  charts/baremetal-csi-plugin/templates/baremetal-csi-controller.yaml
  charts/baremetal-csi-plugin/values.yaml
  cmd/node/main.go
  pkg/base/cache/cache.go
  pkg/base/cache/cache_test.go
  pkg/base/capacityplanner/helpers_test.go
  pkg/base/constants.go
  pkg/base/k8s/cr_helper.go
  pkg/base/k8s/cr_helper_test.go
  pkg/base/k8s/fake_kubeclient.go
  pkg/base/k8s/kubeclient.go
  pkg/base/k8s/kubeclient_test.go
  pkg/base/rpc/grpcclient_test.go
  pkg/common/volume_operations.go
  pkg/common/volume_operations_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/crcontrollers/csibmnode/controller.go
  pkg/crcontrollers/csibmnode/controller_test.go
  pkg/crcontrollers/drive/drivecontroller.go
  pkg/crcontrollers/lvg/lvgcontroller.go
  pkg/crcontrollers/lvg/lvgcontroller_test.go
  pkg/node/node.go
  pkg/node/node_test.go
  pkg/node/provisioners/drive_provisioner.go
  pkg/node/volumemgr.go
  pkg/node/volumemgr_test.go
  pkg/testutils/testutils.go
  test/e2e/scenarios/drive-health-change.go
  variables.mk
Labels: bug, enhancement

#242 [ISSUE-238] Expose volume and partition operations duration
  pkg/common/volume_operations.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/node/provisioners/utilwrappers/partition_operations.go
Labels: enhancement

#241 [ISSUE-240] Implement metrics for volumemgr.Discovery
  pkg/common/volume_operations.go
  pkg/crcontrollers/drive/drivecontroller.go
  pkg/crcontrollers/lvg/lvgcontroller.go
  pkg/metrics/common/reconcile.go
  pkg/metrics/metrics.go
  pkg/node/provisioners/utilwrappers/partition_operations.go
  pkg/node/volumemgr.go
Labels: enhancement

#244 [ISSUE-243] put and remove os labels
  pkg/base/error/types.go
  pkg/base/util/parser.go
  pkg/base/util/parser_test.go
  pkg/crcontrollers/csibmnode/common/const.go
  pkg/crcontrollers/csibmnode/controller.go
  pkg/crcontrollers/csibmnode/controller_test.go
Labels: enhancement

#248 [ISSUE-247] split kind pull images target
  Makefile.validation
Labels: enhancement

#250 [ISSUE-249] Expose build info metrics
  Makefile
  cmd/controller/main.go
  cmd/node/main.go
  pkg/metrics/metrics.go
  variables.mk
Labels: enhancement

#246 [ISSUE-245] Expose ac reservation time in scheduler extender
  charts/scheduler-extender/templates/scheduler-extender.yaml
  charts/scheduler-extender/values.yaml
  cmd/scheduling/extender/main.go
  pkg/base/capacityplanner/helpers.go
Labels: enhancement
