Repository dell/csi-baremetal, pull requests merged in 2022-05, with the labels that each got.

#844 [ISSUE-843] Use Ubuntu 18 as base image
  pkg/node/Dockerfile.build
Labels: bug

#852 [ISSUE-853] Tokenless codecov reporting
  .github/workflows/pr.yml
Labels: chore

#854 [ISSUE-825] Revert changes (#826)
  cmd/drivemgr/loopbackmgr/main.go
  cmd/node/main.go
  devkit/start_ide.sh
  pkg/base/linuxutils/partitionhelper/partition_helper.go
  pkg/base/linuxutils/partitionhelper/partitionhelper_test.go
  pkg/crcontrollers/node/common/annotation.go
  pkg/crcontrollers/node/common/annotation_test.go
  pkg/mocks/provisioners/mock_parititoner.go
  pkg/node/provisioners/drive_provisioner.go
  pkg/node/provisioners/drive_provisioner_test.go
  pkg/node/provisioners/utilwrappers/partition_operations.go
  tests/app/nginx.yaml
  tests/ci.sh
Labels: bug

#855 [ISSUE-839] Use Ubuntu 21.04 as a base image for loopback mgr
  pkg/drivemgr/loopbackmgr/Dockerfile.build
Labels: bug

#850 [ISSUE-849] Call vgs refresh after each lvg-disk reinsert
  pkg/base/linuxutils/lvm/lvm.go
  pkg/eventing/eventing.go
  pkg/mocks/linuxutils/lvm.go
  pkg/node/Dockerfile.build
  pkg/node/volumemgr.go
  pkg/node/volumemgr_test.go
  tests/kind/small-kind.yaml
Labels: bug

#860 [ISSUE-859] Rewrite node-removal documentation
  docs/node-removal.md
Labels: bug

#862 [ISSUE-825] Retry sync partition table with timeout
  cmd/drivemgr/loopbackmgr/main.go
  cmd/node/main.go
  devkit/start_ide.sh
  pkg/base/linuxutils/partitionhelper/partition_helper.go
  pkg/base/linuxutils/partitionhelper/partitionhelper_test.go
  pkg/crcontrollers/node/common/annotation.go
  pkg/crcontrollers/node/common/annotation_test.go
  pkg/mocks/provisioners/mock_parititoner.go
  pkg/node/provisioners/drive_provisioner.go
  pkg/node/provisioners/drive_provisioner_test.go
  pkg/node/provisioners/utilwrappers/partition_operations.go
  tests/app/nginx.yaml
  tests/ci.sh
Labels: bug

#866 Avoid untrusted code execution in e2e workflow
  .github/workflows/e2e.yml
Labels: bug

#864 [ISSUE-863] send MissingDriveReplacementInitiated normal event on DR for OFFLINE disk
  pkg/eventing/eventing.go
  pkg/node/volumemgr.go
  pkg/node/volumemgr_test.go
Labels: bug

#810 [ISSUE-805] Upgrade from 1.0.x to 1.1.x
  docs/CONTRIBUTING.md
  docs/README.md
  docs/crd-lifecycle-of-crd.md
  docs/crds-generation.md
Labels: documentation

#867 [ISSUE-395] CSI must handle deletion of volumes CRs which are in FAILED state
  pkg/node/volumemgr.go
  pkg/node/volumemgr_test.go
  tests/ci.sh
Labels: bug

#848 [ISSUE-845] Update contribution guide
  docs/CONTRIBUTING.md
Labels: documentation
