Repository dell/csi-baremetal, pull requests merged in 2022-02, with the labels that each got.

#722 [ISSUE-690]: disk affinity/antiaffinity proposal refactoring
  docs/proposals/disk-affinity.md
Labels: documentation, enhancement

#723 [ISSUE-713] SANITY_TEST parameter for sanity-ci
  Makefile.validation
  variables.mk
Labels: enhancement

#731 [ISSUE-707] volume release label
  pkg/base/k8s/kubeclient.go
  pkg/base/k8s/kubeclient_test.go
  pkg/common/volume_operations.go
  pkg/common/volume_operations_test.go
  pkg/controller/controller_test.go
Labels: enhancement

#726 [ISSUE-729] Fix issues in long e2e test suite
  test/e2e/common/deploy.go
  test/e2e/scenarios/bare-metal-testdriver.go
  test/kind/kind.yaml
Labels: bug

#720 [ISSUE-717] Generic ephemeral volumes support
  docs/README.md
  pkg/scheduler/extender/extender.go
  pkg/scheduler/extender/extender_test.go
  test/app/nginx-generic-ephemeral.yaml
Labels: documentation, enhancement

#730 [ISSUE-732] Fixed stacked ACR with LVG Volumes on reservation stage
  pkg/base/k8s/kubeclient_test.go
  pkg/common/volume_operations_test.go
  pkg/crcontrollers/reservation/reservationcontroller.go
Labels: bug

#737 [ISSUE-735] CSI GA project status
  docs/README.md
Labels: documentation

#699 [ISSUE-698] volume creation failed by timeout on scale
  pkg/common/volume_operations.go
  pkg/common/volume_operations_test.go
Labels: bug

#741 [ISSUE-740] Add badge with the Go Report
  docs/README.md
Labels: documentation

#742 [ISSUE-702] Bump sidecars versions
  Makefile.validation
  variables.mk
Labels: enhancement

#739 [ISSUE-733] Proposal for distributed tracing of CSI volume requests
  docs/images/create_and_publish_volume.png
  docs/images/delete_volume.png
  docs/images/expand_volume.png
  docs/images/unpublish_volume.png
  docs/proposals/distributed-tracing-of-volume-requests.md
  docs/volume-requests-flow.md
Labels: documentation, enhancement

#746 [ISSUE-745] Wait for reservation to be confirmed
  pkg/scheduler/extender/extender.go
  pkg/scheduler/extender/extender_test.go
Labels: enhancement

#738 [ISSUE-734] Proposal for drive exclusion feature
  docs/proposals/TEMPLATE.md
  docs/proposals/excluding-drives.md
  docs/proposals/images/drive_including.png
Labels: documentation, enhancement

#752 [ISSUE-751] Retry NodeUnpublish after Volume CR update failed
  .github/.codecov.yaml
  pkg/base/k8s/fake_kubeclient.go
  pkg/node/node.go
  pkg/node/node_test.go
Labels: bug

#749 [ISSUE 748] documentation template
  docs/DOC_TEMPLATE.md
  docs/proposals/TEMPLATE.md
Labels: documentation
