Repository dell/csi-baremetal, pull requests merged in 2022-04, with the labels that each got.

#797 [ISSUE-796]: support shorter file paths
  Makefile
  Makefile.validation
  pkg/base/constants.go
  pkg/base/logger/runtime_formatter.go
  pkg/base/logger/runtime_formatter_test.go
  variables.mk
Labels: enhancement

#793 [ISSUE-792] Fix volume creation with corrupted FS
  pkg/base/linuxutils/fs/fs_helper.go
  pkg/base/linuxutils/fs/fs_helper_test.go
  pkg/mocks/linuxutils/fs_helper.go
  pkg/mocks/provisioners/fs_operations.go
  pkg/node/provisioners/drive_provisioner.go
  pkg/node/provisioners/drive_provisioner_test.go
  pkg/node/provisioners/lvm_provisioner.go
  pkg/node/provisioners/lvm_provisioner_test.go
  pkg/node/provisioners/utilwrappers/fs_operations.go
  pkg/node/provisioners/utilwrappers/fs_operations_test.go
Labels: bug

#804 [ISSUE-803] Replace golangci-lint in CSI devkit
  devkit/Dockerfile
Labels: bug

#809 [ISSUE-808] Set custom values for codecov badge color limits
  .github/.codecov.yaml
Labels: documentation

#807 [ISSUE-814] Deprecate Controller_Publish/Unpublish capability
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: bug

#815 [ISSUE-812] Support GA versions in release workflow
  .github/workflows/release.yml
  .github/workflows/tests/pre-release.json
  .github/workflows/tests/release.json
  Makefile.validation
  devkit/Dockerfile
  docs/release-workflow.md
Labels: enhancement

#820 [ISSUE-817] Permission denied error in devkit
  devkit/devkit-entrypoint.sh
Labels: bug

#821 [ISSUE-818] Can't open .md files in devkit
  devkit/Dockerfile
Labels: bug

#823 [ISSUE-822] Deprecate inline volumes
  api/v1/types.proto
  docs/README.md
  pkg/base/linuxutils/partitionhelper/partition_helper.go
  pkg/base/linuxutils/partitionhelper/partitionhelper_test.go
  pkg/base/util/volume_helper.go
  pkg/common/volume_operations.go
  pkg/common/volume_operations_test.go
  pkg/mocks/linuxutils/partitionhelper.go
  pkg/mocks/provisioners/fs_operations.go
  pkg/node/common_test_data.go
  pkg/node/node.go
  pkg/node/node_test.go
  pkg/node/provisioners/drive_provisioner.go
  pkg/node/provisioners/drive_provisioner_test.go
  pkg/node/provisioners/lvm_provisioner.go
  pkg/node/provisioners/lvm_provisioner_test.go
  pkg/node/provisioners/utilwrappers/fs_operations.go
  pkg/node/provisioners/utilwrappers/fs_operations_test.go
  pkg/node/provisioners/utilwrappers/partition_operations.go
  pkg/node/provisioners/utilwrappers/parttiion_operations_test.go
  pkg/scheduler/extender/extender.go
  pkg/scheduler/extender/extender_test.go
  tests/e2e/scenarios/bare-metal-testdriver.go
Labels: documentation, enhancement

#806 [ISSUE-802] Proposal for deploying csi on k3s
  docs/proposals/deploy-csi-to-k3s.md
Labels: documentation, enhancement

#826 [ISSUE-825] Retry sync partition table with timeout
  cmd/drivemgr/loopbackmgr/main.go
  cmd/node/main.go
  devkit/start_ide.sh
  pkg/base/linuxutils/partitionhelper/partition_helper.go
  pkg/base/linuxutils/partitionhelper/partitionhelper_test.go
  pkg/crcontrollers/node/common/annotation.go
  pkg/crcontrollers/node/common/annotation_test.go
  pkg/mocks/provisioners/mock_parititoner.go
  pkg/node/provisioners/drive_provisioner.go
  pkg/node/provisioners/drive_provisioner_test.go
  pkg/node/provisioners/utilwrappers/partition_operations.go
  tests/app/nginx.yaml
  tests/ci.sh
Labels: bug

#831 [ISSUE-839] Update base images for CSI
  pkg/controller/Dockerfile.build
  pkg/crcontrollers/node/Dockerfile
  pkg/drivemgr/basemgr/Dockerfile.build
  pkg/drivemgr/loopbackmgr/Dockerfile.build
  pkg/node/Dockerfile-kernel-5.4.build
  pkg/node/Dockerfile.build
  pkg/scheduler/extender/Dockerfile
  pkg/scheduler/patcher/Dockerfile
  pkg/scheduler/patcher/requirements.txt
  pkg/scheduler/plugin/Dockerfile
Labels: enhancement
