Repository dell/csi-baremetal, pull requests merged in 2022-01, with the labels that each got.

#687 [ISSUE-647] fix event trigger, change zip action
  .github/workflows/e2e.yml
Labels: bug

#693 [ISSUE-692] Bugfix issue volume expand test failed by timeout
  test/e2e/scenarios/bare-metal-testdriver.go
Labels: bug

#695 [ISSUE-691] E2E test results
  .github/workflows/e2e.yml
Labels: bug

#708 [ISSUE-707] volume release label added
  pkg/base/k8s/kubeclient.go
  pkg/base/k8s/kubeclient_test.go
  pkg/common/volume_operations.go
  pkg/common/volume_operations_test.go
  pkg/controller/controller_test.go
Labels: enhancement

#676 [ISSUE-668] no delete AC before lvg removing
  pkg/base/capacityplanner/mocks.go
  pkg/base/k8s/fake_kubeclient.go
  pkg/common/test_data.go
  pkg/common/volume_operations.go
  pkg/common/volume_operations_test.go
  pkg/controller/capacitycontroller/capacitycontroller_test.go
  test/e2e/scenarios/bare-metal-testdriver.go
Labels: enhancement

#694 [ISSUE-690] disk affinity proposal
  docs/proposals/disk-affinity.md
Labels: documentation, enhancement

#689 [ISSUE-688] Bump k8s lib version
  Makefile
  cmd/controller/main.go
  cmd/node/main.go
  cmd/scheduling/extender/main.go
  cmd/scheduling/scheduler/main.go
  go.mod
  go.sum
  pkg/base/k8s/cr_helper.go
  pkg/base/k8s/fake_kubeclient.go
  pkg/base/k8s/kubecache.go
  pkg/base/k8s/kubeclient.go
  pkg/base/k8s/kubeclient_test.go
  pkg/controller/capacitycontroller/capacitycontroller.go
  pkg/controller/capacitycontroller/capacitycontroller_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/crcontrollers/drive/drivecontroller.go
  pkg/crcontrollers/lvg/lvgcontroller.go
  pkg/crcontrollers/lvg/lvgcontroller_test.go
  pkg/crcontrollers/node/controller.go
  pkg/crcontrollers/node/controller_test.go
  pkg/crcontrollers/reservation/reservationcontroller.go
  pkg/events/mocks/EventInterface.go
  pkg/mocks/k8sclient.go
  pkg/node/node_test.go
  pkg/node/volumemgr.go
  pkg/node/volumemgr_test.go
  pkg/scheduler/extender/extender_test.go
  pkg/scheduler/plugin/plugin.go
  test/e2e/common/deploy.go
  test/e2e/common/util.go
  test/e2e/scenarios/bare-metal-testdriver.go
  test/e2e/scenarios/controller-node-fail.go
  test/e2e/scenarios/different-sc-test.go
  test/e2e/scenarios/drive-health-change.go
  test/e2e/scenarios/node-reboot.go
  test/e2e/scenarios/scheduler-test.go
  test/e2e/scenarios/setup.go
  test/e2e/scenarios/stress-test.go
  variables.mk
Labels: enhancement

#711 [ISSUE-709] Improve release workflow
  .github/workflows/release.yml
  docs/images/release_workflow.png
  docs/release-workflow.md
Labels: enhancement

#716 [ISSUE-713] Add new target for k8s compatibility testing
  Makefile.validation
  docs/README.md
Labels: enhancement
